//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sells
    {
        public int ID { get; set; }
        public Nullable<int> StuffID { get; set; }
        public Nullable<int> TovarID { get; set; }
        public string KOlVoTOvarov { get; set; }
    
        public virtual Stuffs Stuffs { get; set; }
        public virtual Tovari Tovari { get; set; }
    }
}
