//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sells
    {
        public System.Guid IDSell { get; set; }
        public System.Guid StuffID { get; set; }
        public System.Guid TovarID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Stuffs Stuffs { get; set; }
        public virtual Tovari Tovari { get; set; }
    }
}
